In [1]:
import numpy as np
import os
from preprocessing.dataset_class import DummyDataset
from tqdm.notebook import tqdm
import torch
import torchvision
import torchvision.transforms as transforms
from PIL import Image

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
def calculate_mean_and_std(data_dirs):
    all_images = []
    count = 0
    for data_dir in data_dirs:
        if os.path.isdir(data_dir):
            all_files = os.listdir(data_dir)
            for file_name in tqdm(all_files):
                if ".jpg" in file_name:
                    all_images.append(os.path.join(data_dir, file_name))
   
    print(len(all_images))
    return all_images


In [4]:
all_images = calculate_mean_and_std(["data/msimut", "data/mss"])


192312


In [5]:
dataset = DummyDataset(all_images)

In [6]:
trainloader = torch.utils.data.DataLoader(dataset, batch_size = 1000, shuffle = False, num_workers = 2)

In [7]:
pop_mean = []
pop_std0 = []
pop_std1 = []
for images in trainloader:
    # shape (batch_size, 3, height, width)
    numpy_image = images.numpy()
    
    # shape (3,)
    batch_mean = np.mean(numpy_image, axis=(0,2,3))
    batch_std0 = np.std(numpy_image, axis=(0,2,3))
    batch_std1 = np.std(numpy_image, axis=(0,2,3), ddof=1)
    
    pop_mean.append(batch_mean)
    pop_std0.append(batch_std0)
    pop_std1.append(batch_std1)

# shape (num_iterations, 3) -> (mean across 0th axis) -> shape (3,)
pop_mean = np.array(pop_mean).mean(axis=0)
pop_std0 = np.array(pop_std0).mean(axis=0)
pop_std1 = np.array(pop_std1).mean(axis=0)

In [8]:
pop_mean

array([0.7265438 , 0.5136047 , 0.69041806], dtype=float32)

In [9]:
pop_std0

array([0.15620758, 0.20168874, 0.14780489], dtype=float32)

In [10]:
pop_std1

array([0.15620758, 0.20168874, 0.14780489], dtype=float32)